# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CloudDetectionPlugin
                                 A QGIS plugin
 Plugin for detecting clouds in satellite imagery using ML algorithms
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-04
        copyright            : (C) 2025 by Yana Bakhramkhan
        email                : yana@qgis.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CloudDetectionPlugin class from file CloudDetectionPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cloud_detection import CloudDetectionPlugin
    return CloudDetectionPlugin(iface)
